FORMAT: 1A

# gmi-presenter
GMI Toolbox API

# Group Mode
Center Mode control

## Mode Collection [/mode]
### List all Assets [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "title": "p1"
        }, {
          "id": 2, "title": "p2"
        }]
  
## Mode Select [/mode/{id}]

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Mode to perform action with.

### Set Mode Active [PUT]
+ Response 200 (application/json)
    + Body
    
            { "status": "ok" }

# Group Feed
Feed control

## Feed Collection [/feed]
### List all Feeds [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "title": "p1"
        }, {
          "id": 2, "title": "p2"
        }]
  
## Feed Select [/feed/select/{id}]

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Mode to perform action with.

### Set Feed Active [PUT]
+ Response 200 (application/json)
    + Body
    
            { "status": "ok" }

# Group Visits
Visit related resources of the **Visits API**

## Visits Collection [/visit]
### List all Visits [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "title": "p1"
        }, {
          "id": 2, "title": "p2"
        }]
            
## Visit [/visit/{id}]
A single Visit object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Visit to perform action with.

### Retrieve a Visit [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }
            
# Group Panorama
Panorama application control

## Panorama Collection [/panorama]
### List all Panoramas [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "title": "p1"
        }, {
          "id": 2, "title": "p2"
        }]
  
## Panorama Active [/panorama/activate/{id}]      
### Set Panorama Active [PUT]
+ Response 200 (application/json)
    + Body
    
            { "status": "ok" }

## Panorama Close [/panorama/close/{id}]      
### Close Active Panorama [PUT]
+ Response 200 (application/json)
    + Body
    
            { "status": "ok" }

# Group Consumer Insight
Consumer Insight application control

## Consumer Insight Collection [/insight]
### List all Consumer Insights [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "title": "p1"
        }, {
          "id": 2, "title": "p2"
        }]
  
## Consumer Insight Active [/insight/activate/{id}]      
### Set Consumer Insight Active [PUT]
+ Response 200 (application/json)
    + Body
    
            { "status": "ok" }

## Consumer Insight Close [/insight/close/{id}]      
### Close Active Panorama [PUT]
+ Response 200 (application/json)
    + Body
    
            { "status": "ok" }

# Group Assets
Asset control

## Asset Collection [/asset]
### List all Assets [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "title": "p1"
        }, {
          "id": 2, "title": "p2"
        }]
  
## Asset Select [/asset/select/{id}]      
### Set Consumer Insight Active [PUT]
+ Response 200 (application/json)
    + Body
    
            { "status": "ok" }

## Asset Move [/asset/move/{id}/display/{displayid}]      
### Close Active Panorama [PUT]
+ Response 200 (application/json)
    + Body
    
            { "status": "ok" }

# Group Presentations
Presentation related resources of the **Presentations API**

## Presentations Collection [/presentations]
### List all Presentations [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "title": "p1"
        }, {
          "id": 2, "title": "p2"
        }]
            
## Presentation [/presentations/{id}]
A single Presentation object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Presentation to perform action with.

### Retrieve a Note [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }

### Update a Presentation [PUT]
+ Response 405

